### ISSUE TITLE
Overall Plan

### ISSUE THREAD

**Issue by adlternative** [adlternative/tinygithub#4]
## Project Goals and Objectives

implement a simple code server like github.

## Milestones
We plan to divide the work into the following stages...

- [x] Milestone 1: user auth
    - [x] login
    - [x] register
    - [x] logout
- [x] Milestone 2: user repository interaction
    - [x] show user's repositories
    - [x] show one repository
        - [x] blame tree
        - [x] about section
        - [x] revision selection
        - [x] clone button
    - [x] create one repository
    - [x] remove one repository  
- [ ] Milestone 3: container
- [ ] Milestone 4: https
- [ ] Milestone 5: code search
